// <auto-generated />
using System;
using EternalStore.DataAccess.StoreManagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EternalStore.DataAccess.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20191110034108_StoreReset")]
    partial class StoreReset
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EternalStore.Domain.StoreManagement.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idCategory")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsEnabled")
                        .HasColumnName("isEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("categories_tb");
                });

            modelBuilder.Entity("EternalStore.Domain.StoreManagement.Product", b =>
                {
                    b.Property<int>("IdCategory")
                        .HasColumnName("idCategory")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnName("idProduct")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnName("price")
                        .HasColumnType("decimal");

                    b.Property<int?>("idCategory")
                        .HasColumnName("Product_idCategory")
                        .HasColumnType("int");

                    b.HasKey("IdCategory", "Id");

                    b.HasIndex("idCategory");

                    b.ToTable("products_tb");
                });

            modelBuilder.Entity("EternalStore.Domain.StoreManagement.Product", b =>
                {
                    b.HasOne("EternalStore.Domain.StoreManagement.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("idCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
